### ISSUE TITLE
PID in initprocess of container is not reflect to the container

### ISSUE THREAD

**Issue by AhmedHanafy725** [threefoldtech/0-templates#205] opened 2018-11-08 13:25 UTC
### information
```
container_data = {'nics': [{'type': 'default', 'name': 'defaultnic'}], 'flist': 'https://hub.grid.tf/tf-bootable/ubuntu:16.04.flist', 'storage': 'zdb://hub.grid.tf:9900', 'mounts': [], 'initProcesses': [{'name': 'sleep', 'args': ['1000s'], 'id': '3777'}], 'hostNetwprking': False, 'hostname': '5d4ec9b76c3c48fbbccbe0', 'ports': [], 'zerotierNetwork': '', 'privileged': False, 'env': []}
```
### Steps:
1- create container with this data.

### Actual Result
The initprocess is created, but the PID is different from PID in data (should be 3777)

![pid](https://user-images.githubusercontent.com/41957921/48200166-f74d2e80-e366-11e8-98c0-15ea58099153.png)

**Comment by delandtj** [comment] 2018-11-11 11:38
err .... NO!
a process in a container lives in the CONTAIER's process table.
the container 1 (the host) sees all processes in his own table, but from his own view.
This is not a bug,but a feature ;-)
plz close this, to be never spoken of again.

**Comment by serboctor** [comment] 2018-11-11 13:58
@AhmedHanafy725 the id in the init_processes is used for the job id, it doesn't set the process id. The readme of the container service seems to have incorrect info. I'll close the ticket and update the readme.

**Closed by serboctor** 2018-11-11 13:58 UTC
Labels: type_bug
