### ISSUE TITLE
After restarting tlog service for many times, Minio still point to an old one

### ISSUE THREAD

**Issue by 0xIslamTaha** [threefoldtech/0-templates#179] opened 2018-10-23 14:01 UTC
**Hint**
I had to do this scenario too many times to produce this bug

**Related test cases**
```
nosetests-3.4 -vs --logging-level=WARNING testcases/test_tlog.py
```

**Descriptions**
After restarting tlog service many times, Minio still point to an old one

**Steps**
- Restart tlog service many times 
- Check s3.minio_config 
- List namespaces under tlog zdb, It should match the one in s3.minio_config

**Actual Result**
```
In [49]: print(s3.minio_config)
namespace: namespace
password: 445t5b3gnx2ydkv1smjrvmflwu6s58pe
datastor: # required
  shards: # required
    - 10.102.234.243:1050
    - 10.102.114.69:1034
    - 10.102.178.130:1051
  pipeline:
    block_size: 1048576
    compression: # optional, snappy by default
      type: snappy # snappy is the default, other options: lz4, gzip
      mode: default # default is the default, other options: best_speed, best_compression
    encryption: # optional, disabled by default
      type: aes # aes is the default and only standard option
      private_key: 
    distribution:
      data_shards: 1
      parity_shards: 1
minio:
  tlog:
    address: 10.102.96.237:1044
    namespace: namespace_tlog
    password: 445t5b3gnx2ydkv1smjrvmflwu6s58pe
```

```
╭─xtremx@xtrem-x /opt/code/github/threefoldtech/minio  ‹failures_testsuite*› 
╰─$ redis-cli -h 10.102.96.237 -p 1044
10.102.96.237:1044> nslist
1) "default"
2) "ee49471d-fefe-4eea-9aca-3b7d0370e9a8"
10.102.96.237:1044> 
10.102.96.237:1044> nslist
1) "default"
2) "ee49471d-fefe-4eea-9aca-3b7d0370e9a8"
(0.69s)
10.102.96.237:1044> 


```

**Repos**
development

**Comment by muhamadazmy** [comment] 2018-11-06 12:11
- I don't believe restarting the tlog server is the cause of the issue. If tlog config is wrong, then it's probably wrong since the start.
- We recently were working around S3 setup, this includes tlog and installation were consistent from the start.
- Can you clarify if:
 - The namespace existed before restarting zero-db
 - The config was correct before restarting zero-db
 - Changes that happened to both config and zdb after the restart.

**Comment by muhamadazmy** [comment] 2018-11-12 14:32
I checked the code, and tried to reproduce this myself and here is my `hypothesis` (it's not a theory since i can't prove it)

By the time of this comment this issue was 20 days old. While this [PR here](https://github.com/threefoldtech/0-templates/pull/185) is only 14 days old. The PR fixes a port reservation issue. basically it prevents other services from reusing the port as long as the consumer service (in this case zdb) was not deleted permanently.

My hypothesis is that, when the zdb was stopped, another job scheduled a zdb installation on the same node that picked the same port (`1044` in our case) to be it's own port since it was the first free port available. When u started zdb it probably picked another port.

While u were trying to reconnect, u actually landed on a different zdb than the first one, hence the namespace does not exist.

I think this issue now is FIXED, but I won't close it unless you confirm you can not reproduce.

**Comment by 0xIslamTaha** [comment] 2018-11-19 11:45
@Pishoy here r the verification steps:
```
verification steps:
1- create s3 
2- get tlog zdb
3- connect to it via Redis-cli tool
4- list namespaces and make shure that tlog namespace is there
5- stop this zdb service through its 0robot
6- start thsi zdb service throuth its 0robot
7- Repeat (4:6) for 5 times
```

**Comment by Pishoy** [comment] 2018-11-19 13:19
verified , and the namespace still exist after restart its zerodb
```
In [30]: zdb
Out[30]: robot://test/github.com/threefoldtech/0-templates/zerodb/0.0.1?guid=f6f7a44d-95e8-4039-a86a-2f1f18cdb80b&name=ace62cf1-b984-4af7-bd12-d439aa93d50b

In [31]: zdb.schedule_action('stop').wait(die=True)
Out[31]: stop

In [32]: zdb.schedule_action('start').wait(die=True)
Out[32]: start

In [33]: zdb.schedule_action('stop').wait(die=True)
Out[33]: stop

In [34]: zdb.schedule_action('start').wait(die=True)
Out[34]: start

In [35]: zdb.schedule_action('stop').wait(die=True)
Out[35]: stop

In [36]: zdb.schedule_action('start').wait(die=True)
Out[36]: start

In [37]: zdb.schedule_action('stop').wait(die=True)
Out[37]: stop

In [38]: zdb.schedule_action('start').wait(die=True)
Out[38]: start

In [39]: zdb.schedule_action('stop').wait(die=True)
Out[39]: stop

In [40]: zdb.schedule_action('start').wait(die=True)
Out[40]: start
```
```
root@e7605ba47d5c:~# redis-cli -h 10.102.40.95 -p 1038

10.102.40.95:1038> nslist
1) "default"
2) "2e76e192-d19a-41ee-bf30-fabc1d99c3ac_tlog"
10.102.40.95:1038> nslist
Error: Connection timed out
root@e7605ba47d5c:~# redis-cli -h 10.102.40.95 -p 1038
10.102.40.95:1038> nslist
1) "default"
2) "2e76e192-d19a-41ee-bf30-fabc1d99c3ac_tlog"

10.102.40.95:1038> nslist
1) "default"
2) "2e76e192-d19a-41ee-bf30-fabc1d99c3ac_tlog"
(263.65s)
10.102.40.95:1038> nslist
Error: Connection timed out
root@e7605ba47d5c:~# redis-cli -h 10.102.40.95 -p 1038
10.102.40.95:1038> nslist
1) "default"
2) "2e76e192-d19a-41ee-bf30-fabc1d99c3ac_tlog"

root@e7605ba47d5c:~# redis-cli -h 10.102.40.95 -p 1038

Could not connect to Redis at 10.102.40.95:1038: Connection timed out

not connected> 
root@e7605ba47d5c:~# redis-cli -h 10.102.40.95 -p 1038
10.102.40.95:1038> nslist
1) "default"
2) "2e76e192-d19a-41ee-bf30-fabc1d99c3ac_tlog"
10.102.40.95:1038> 
```

**Closed by Pishoy** 2018-11-19 13:19 UTC
Labels: state_verification, type_bug
